# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-07 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20171005_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default=2, upload_to='teacher/%Y/%m', verbose_name='老师头像'),
            preserve_default=False,
        ),
    ]
