# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-02 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20171002_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='courses',
            new_name='course',
        ),
    ]
